package asentric

import "time"

// Severity represents alert severity level.
// This is a strict set of values - only these are valid.
type Severity string

const (
	SeverityCritical Severity = "CRITICAL"
	SeverityHigh     Severity = "HIGH"
	SeverityMedium   Severity = "MEDIUM"
	SeverityLow      Severity = "LOW"
	SeverityInfo     Severity = "INFO"
)

// ExecutionRef holds reference to the blockchain execution context.
type ExecutionRef struct {
	TxHash      string
	BlockNumber uint64
	LogIndex    int
}

// Alert represents a security alert generated by a rule.
type Alert struct {
	// Rule is the name of the rule that generated this alert
	Rule string

	// Severity indicates the severity level
	Severity Severity

	// Legacy fields (used by engine.go)
	Summary   string
	Evidence  *Event
	Timestamp time.Time

	// New fields for builder pattern
	Title       string
	Description string
	Metadata    map[string]interface{}
	Ref         *ExecutionRef
}

// NewAlert creates a new Alert with required fields.
// Timestamp is automatically set to current time.
func NewAlert(ruleID, title string, severity Severity) *Alert {
	return &Alert{
		Rule:      ruleID,
		Title:     title,
		Severity:  severity,
		Timestamp: time.Now(),
		Metadata:  make(map[string]interface{}),
	}
}

// WithDescription sets the alert description.
// Returns self for method chaining.
func (a *Alert) WithDescription(desc string) *Alert {
	a.Description = desc
	return a
}

// WithMetadata adds key-value pairs to the alert metadata.
// Returns self for method chaining.
// Existing keys will be overwritten.
func (a *Alert) WithMetadata(key string, value interface{}) *Alert {
	if a.Metadata == nil {
		a.Metadata = make(map[string]interface{})
	}
	a.Metadata[key] = value
	return a
}

// WithRef sets the execution reference (tx hash, block, log index).
// Returns self for method chaining.
func (a *Alert) WithRef(ref *ExecutionRef) *Alert {
	a.Ref = ref
	return a
}

// NewExecutionRef creates a new ExecutionRef.
func NewExecutionRef(txHash string, blockNumber uint64, logIndex int) *ExecutionRef {
	return &ExecutionRef{
		TxHash:      txHash,
		BlockNumber: blockNumber,
		LogIndex:    logIndex,
	}
}

// String returns severity as string representation.
func (s Severity) String() string {
	return string(s)
}
